# ------------------------------------------------------- #
# Note: this file originates in action-composite-template #
# ------------------------------------------------------- #

services:
  # ---- mega-linter ---- #
  lint:
    image: oxsecurity/megalinter-documentation:v7.3.0
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- readme generator ---- #
  readme:
    image: pandoc/minimal:2.19
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml

  # ---- action container ---- #
  action:
    profiles: ["action"]
    build: .

  # ---- main container ---- #
  code:
    profiles: ["code"]
    image: python:3.8-alpine
    working_dir: /code
    entrypoint: ./entrypoint.sh || echo $?
    command: [start]
    tty: true
    volumes:
      - ./:/code

  app-test:
    extends: code
    profiles: ["test"]
    command: run test:ci -- --reporter=classic
